export const PRODUCT_LIST_REQUEST = "PRODUCT-LIST-REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT-LIST-SUCCESS";
export const ADD_TO_CART = "ADD-TO-CART";
export const REMOVE_FROM_CART = "REMOVE-FROM-CART";
